### ISSUE TITLE
I[1](MAQ):RESPONSIVE VISTA SEARCH

### ISSUE THREAD

**Issue by elenaJO** [apprunn/dp6WebDatosPeru#46]
**Topic**
#1 

**Description**
Responsive vista search

**Acceptance Test**
N/A

**Implementation Notes**
none

**Subtasks**
N/A

**Planning Estimate**
1

**References**
N/A

**Latest Assets**
https://app.zeplin.io/project/5a822dd855a7acf930973b1b/screen/5afb4245f10c455a42070b28

**Comment by AzulChic** [comment]
Fixes on #47
